### ISSUE TITLE
Does it even work with MongoDB 2.x?

### ISSUE THREAD

**Issue by peterbe** [dcrosta/professor#6]
I must be tired. I wish I could delete the issue.

**Comment by dcrosta** [comment]
Glad you figured it out. As you probably determined, I think this is mainly an issue of lacking documentation compounded by confusing naming within the codebase (the `databases` collection looks and sounds like something MongoDB would provide, and overlaps at least conceptually with the `show databases` shell command, etc). If you'd like to take a stab at #3 based on your experience setting up Professor, I'd be very grateful!

**Comment by peterbe** [comment]
I was just tired. I couldn't figure out how the collection of tables were populated. After a lot of wasted time I remembered, I had to go to the web interface on :8080 and add one manually. 

Personally I think the scripts.py could do that for you the first time.

**Comment by peterbe** [comment]
...if that's even possible.

**Comment by dcrosta** [comment]
It is not currently possible, but definitely a good idea.
